const animes = [
  {
    nome: "Sono Bisque Doll wa Koi wo Suru",
    nota: 8.0,
    imdb: 8.0,
    dublado: true,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "12/24",
    img: "https://m.media-amazon.com/images/M/MV5BYmJhYjgzYTQtMzMxYi00NTkyLWI2MWItNTgxNjk1NzU0YmQzXkEyXkFqcGc@._V1_.jpg",
    desc: "Bem legal, ele consegue colocar romance sem deixar meloso, trazendo um tema que fica legal de acompanhar, e tem bastante ecchi.",
    genre: "1, 4, 9"
  },
  {
    nome: "Kimetsu no Yaiba",
    nota: 8.8,
    imdb: 8.6,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "63/63", 
    img: "https://m.media-amazon.com/images/M/MV5BMWU1OGEwNmQtNGM3MS00YTYyLThmYmMtN2FjYzQzNzNmNTE0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Você pensa que é um vídeo da vida real até ver o Tanjiro kkk, no geral é bem legal e bonito, e segue bem a receita básica de shōnen, o que é bom",
    genre: "2, 7, 10"
  },
  {
    nome: "Dandadan",
    nota: 8.5,
    imdb: 8.3,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "24/24", 
    img: "https://m.media-amazon.com/images/M/MV5BYWFhOWMxNTYtZThiMi00ZmQ5LTlmODktN2QwNzUyZjMyZGQzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Muita informação xD. Tirando a brincadeira, é realmente um anime confuso no começo, porque ele joga muita coisa na sua cara do nada, mas dps ele fica MUITO bom e divertido. Obs.: tem um humor bem quinta série kk",
    genre: "1, 2, 4"
  },
  {
    nome: "Frieren: Beyond Journey's End",
    nota: 9.3,
    imdb: 8.9,
    dublado: true,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: true,
    eps: "28/38", 
    img: "https://m.media-amazon.com/images/M/MV5BZTI4ZGMxN2UtODlkYS00MTBjLWE1YzctYzc3NDViMGI0ZmJmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Ele consegue alternar entre tranquilidade e ação sem dificuldades, o universo é muito bem construído e pensado.",
    genre: "6, 7, 9"
  },
  {
    nome: "Fullmetal Alchemist: Brotherhood",
    nota: 9.5,
    imdb: 9.1,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: true,
    eps: "64/64", 
    img: "https://m.media-amazon.com/images/M/MV5BMzNiODA5NjYtYWExZS00OTc4LTg3N2ItYWYwYTUyYmM5MWViXkEyXkFqcGc@._V1_QL75_UY281_CR6,0,190,281_.jpg",
    desc: "Ele começa bem, o meio é ótimo, e o final é perfeito.",
    genre: "2, 7, 10"
  },
  {
    nome: "Fire Force",
    nota: 7.5,
    imdb: 7.6,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "73/73", 
    img: "https://m.media-amazon.com/images/M/MV5BMThhODExMTUtZmIyMC00OTY4LTk5YWMtN2YxYWRhNmNiNDNmXkEyXkFqcGc@._V1_.jpg",
    desc: "Enrola muito e tem brigas que começam sem motivo e terminam sem um porquê, mas as lutas são bem bonitas e é engraçado. Devo admitir que eles sabem fazer um bom gancho pro próximo episódio, então é difícil não querer continuar assistindo. Porém, no final, começa a ficar BEM viajado, e o desfecho é BEM anticlimático.",
    genre: "2, 8, 10"
  },
  {
    nome: "Assassination Classroom",
    nota: 7.5,
    imdb: 8.3,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "47/47", 
    img: "https://m.media-amazon.com/images/M/MV5BZjBkYmRiOTAtY2IwOS00ZWU3LTk3YjItNjMzYWZiMDE1MjcyXkEyXkFqcGc@._V1_.jpg",
    desc: "Ideia legal, final legal, lore legal e Plots legais, pena que tem tantos episódios desnecessários que não dá vontade nenhuma de assistir.",
    genre: "4, 8, 10"
  },
  {
    nome: "The Greatest Demon Lord Is Reborn as a Typical Nobody",
    nota: 7.5,
    imdb: 6.3,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "12/12", 
    img: "https://m.media-amazon.com/images/M/MV5BZTE0ZmQ0ZmYtYjllZS00MDg0LTk3YzMtYzBhMDk4ZjUzNzAyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Isekai/10 Não tem nada de especial, mas não é ruim.",
    genre: "5, 7"
  },
  {
    nome: "Miss Kobayashi's Dragon Maid",
    nota: 6.0,
    imdb: 7.7,
    dublado: true,
    finalizado: false,
    emLancamento: false,
    dropado: true,
    brutal: false,
    eps: "03/25", 
    img: "https://m.media-amazon.com/images/M/MV5BZTM2MmRjOTYtMTgwNS00NDUyLTk0Y2YtNTZkMjZkOTE0OTdlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "De maneira alguma é ruim, só não é meu estilo, Slice of Life não me pega tanto, mas é engraçado pelos episódios que assisti.",
    genre: "4, 7, 9"
  },
  {
    nome: "A.I.C.O. Incarnation",
    nota: 7.0,
    imdb: 6.3,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "12/12", 
    img: "https://m.media-amazon.com/images/M/MV5BMTZiNGYzZjktODViMi00ZWJjLWExMTMtMGNkYzQ1ODVhNTE2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Não é ruim, mas não tem nada de especial, meio sem sal. Mas vale a pena assistir (Podia ter um final melhor, menos genérico).",
    genre: "2, 8"
  },
  {
    nome: "Horimiya",
    nota: 3.5,
    imdb: 8.0,
    dublado: true,
    finalizado: false,
    emLancamento: false,
    dropado: true,
    brutal: false,
    eps: "13/26", 
    img: "https://m.media-amazon.com/images/M/MV5BNGFjM2M0MTYtM2IxMi00MWQ0LWIyNTYtMGE0YzAyMjA1N2ZhXkEyXkFqcGc@._V1_.jpg",
    desc: "Romance não é um gênero de que eu gosto, e o anime é puro romance adolescente, melação e história mexicana, e piora na segunda temporada que para o foco nos protagonistas e foca nos NPCs.",
    genre: "1, 9"
  },
  {
    nome: "The Weakest Tamer Began a Journey to Pick Up Trash",
    nota: 8.0,
    imdb: 7.0,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "12/12", 
    img: "https://m.media-amazon.com/images/M/MV5BMGFiNzEwNTAtNGQ4Ni00YWZmLWFmNjEtNmZjOGNhMWFhYzgwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Um Isekai Be Like, porém acho que por conta da protagonista ser criança, você se apega mais a personagem e torce para tudo dar certo com ela.",
    genre: "5, 7, 9"
  },
  {
    nome: "KonoSuba: God's Blessing on This Wonderful World!",
    nota: 9.5,
    imdb: 7.8,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: true,
    eps: "31/31", 
    img: "https://m.media-amazon.com/images/M/MV5BNTQ5NzJjMjgtNDliNC00YTdmLWJiOTQtYWRiMzY4OWU5NGQ3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Melhor Isekai que já assisti, paródia de Isekai com Ecchi, BRUTAL.",
    genre: "3, 4, 5, 7"
  },
  {
    nome: "My Unique Skill Makes Me OP Even at Level 1",
    nota: 7.5,
    imdb: 6.2,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "12/12", 
    img: "https://m.media-amazon.com/images/M/MV5BOTM4YWQzNGEtZTBiZi00NGIyLWE2NDQtMjcyYzM4NWFmN2Q2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Isekai/10 Eu Inhamo a Cenoura do Level Baixo.",
    genre: "4, 5, 7"
  },
  {
    nome: "I Got a Cheat Skill in Another World and Became Unrivaled in The Real World, Too",
    nota: 7.5,
    imdb: 6.4,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "13/13", 
    img: "https://m.media-amazon.com/images/M/MV5BZWExYjA3OTAtYzliNC00MWMzLWI1NmYtYWY0MDRhNGIyN2IwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Isekai/10 Bem legal o estilo artístico trocando entre os mundos. A história é de isekai, não tem como fugir.",
    genre: "2, 5, 7"
  },
  {
    nome: "That Time I Got Reincarnated as a Slime",
    nota: 9.0,
    imdb: 8.1,
    dublado: true,
    finalizado: false,
    emLancamento: true,
    dropado: false,
    brutal: true,
    eps: "72/72", 
    img: "https://m.media-amazon.com/images/M/MV5BOTczMjM3MDUtYmZjMC00YzZhLWE4ODQtNjg5YWU4NTJjNzY2XkEyXkFqcGc@._V1_.jpg",
    desc: "Segundo melhor isekai que já assisti, muito interessante a ideia, o único defeito é a falta de consequências, mas tirando isso, é muito bom!",
    genre: "2, 5, 7, 10"
  },
  {
    nome: "The Unwanted Undead Adventurer",
    nota: 7.5,
    imdb: 7.2,
    dublado: false,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "12/12", 
    img: "https://m.media-amazon.com/images/M/MV5BZTJlMzc5NTgtN2U3Ny00ZGE3LTlkMGQtYTA2ZTg1NThhZjIwXkEyXkFqcGc@._V1_.jpg",
    desc: "Bom, tem uma ideia legal, pena que acaba muito cedo, com MUITAS pontas soltas e MUITAS coisas sem explicação.",
    genre: "2, 7"
  },
  {
    nome: "Kaguya-sama: Love Is War",
    nota: 7.7,
    imdb: 8.5,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "43/43", 
    img: "https://m.media-amazon.com/images/M/MV5BMTM1ZWViNWMtZWY2ZC00YmYyLTk1ZGEtMzRjOWI2YTM1OTI3XkEyXkFqcGc@._V1_.jpg",
    desc: "As duas primeiras temporadas são MUITO boas, conseguem misturar romance com comédia de uma maneira espetacular, porém... da terceira temporada para a frente começa a focar muito mais no romance, o que já me perde um pouco. (obs. Da terceira temporada para a frente, o anime tem MUITAS indiretas/diretas de sexo, o que não me agrada tanto).",
    genre: "1, 4, 9"
  },
  {
    nome: "Tomo-chan Is a Girl!",
    nota: 7.0,
    imdb: 7.5,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "13/13", 
    img: "https://m.media-amazon.com/images/M/MV5BMzQxMzg3N2EtN2MzNC00ZTg0LWJhNGYtZWU2Y2RlZTg1MGNlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "É engraçadinho, é romance mas não achei ruim, principalmente porque tem poucos episódios e um final aceitável.",
    genre: "1, 4, 9"
  },
  {
    nome: "Sword Art Online",
    nota: 8.5,
    imdb: 7.5,
    dublado: true,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "25/96", 
    img: "https://m.media-amazon.com/images/M/MV5BN2NhYzU2NDEtYzI1NS00MjgzLThjZGUtOTYxNGJkZjZmNDdjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Ideia boa, Isekai Be Like e as ações tem peso relativamente, porém tem um desequilíbrio nas lutas e cenas EXTREMAMENTE desconfortáveis.",
    genre: "2, 5, 7, 8"
  },
  {
    nome: "Neon Genesis Evangelion",
    nota: 5.0,
    imdb: 8.5,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "26/26", 
    img: "https://m.media-amazon.com/images/M/MV5BZjZjZGI3ZDQtODNmZC00NjE0LTlmYTUtOTljMWI2YjNmMTQ0XkEyXkFqcGc@._V1_.jpg",
    desc: "Superestimado, começa legal mas da metade pra frente escaralha tudo. É um anime que dá sono, principalmente nas partes finais onde não acontece nada, e eu não vou assistir vídeo pra entender a LORE.",
    genre: "6, 8"
  },
  {
    nome: "Dr. Stone",
    nota: 8.0,
    imdb: 8.1,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "95/95", 
    img: "https://m.media-amazon.com/images/M/MV5BYzZkYjM1MWMtNTY3Mi00MTMzLTlhNmQtN2ExZjFkYzdjZmFjXkEyXkFqcGc@._V1_.jpg",
    desc: "Bom anime. A 1ª temporada é BRUTAL, porem da segunda pra frente continua legal mas exagera um pouco nas criações e o final poderia ser levemente mais ''REALISTA'' mas é um anime realmente bom!",
    genre: "4, 8, 10"
  },
  {
    nome: "The Apothecary Diaries",
    nota: 0.0,
    imdb: 8.5,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/48", 
    img: "https://m.media-amazon.com/images/M/MV5BNjAxMmFjZjgtYjM1ZS00NzdmLTliZDktZmIyMzU5YTBlNDBmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "???",
    genre: "6"
  },
  {
    nome: "ONIMAI: I'm Now Your Sister!",
    nota: 0.0,
    imdb: 7.0,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: true,
    brutal: false,
    eps: "1/12", 
    img: "https://m.media-amazon.com/images/M/MV5BYWY4Yzk4M2ItNGMxMi00YWM3LWFlNzAtMzZiNWM5Y2FlNDllXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Olha, esse anime não é destinado pro meu nicho; e eu não veria nem se me pagassem. É um negócio esquisito demais. Eu não vou nem dar nota pra isso.",
    genre: "4, 9"
  },
  {
    nome: "KonoSuba: An Explosion on This Wonderful World!",
    nomeOriginal: "KonoSuba: An Explosion on This Wonderful World!",
    nota: 9.0,
    imdb: 7.0,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: true,
    eps: "12/12", 
    img: "https://m.media-amazon.com/images/M/MV5BYTRiM2VmNjgtZWY5ZS00YTIxLWJhMjAtY2UzYTk3NzM5ZTM2XkEyXkFqcGc@._V1_.jpg",
    desc: "Spin-off brutal! Diferente de Konosuba, o foco não é comédia, mas a história da Megumin é sensacional. E ver o trio principal ao fundo das cenas é foda demais. Nostalgia absurda.",
    genre: "4, 5, 7"
  },
  {
    nome: "Akashic Records of Bastard Magic Instructor",
    nota: 8.2,
    imdb: 7.0,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "12/12", 
    img: "https://m.media-amazon.com/images/M/MV5BODgwMGJkZWEtNzFjMS00OTlkLTg0MjMtMTY5NmFjZmUwMjJjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Maior decepção até agora. O anime é BOM D+ Mas deixou MUITA coisa sem explicar e preparou TUDO pra 2ª temporada… que nunca vai vir. JÁ FAZ 7 ANOS DO LANÇAMENTO DESSA DESGRAÇA!",
    genre: "3, 4, 7"
  },
  {
    nome: "Hell's Paradise",
    nota: 7.8,
    imdb: 8.1,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "25/25", 
    img: "https://m.media-amazon.com/images/M/MV5BZjhmMjhkNjUtMGU2MC00N2IzLTg1YzItZDk5ODMxMDYxODc0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Ótimo anime. O estilo artístico é incrível e as batalhas são extremamente bonitas. Uma pena que a história ainda não foi finalizada.",
    genre: "2, 7, 10"
  },
  {
    nome: "Yamada-kun to Lv999 no Koi wo Suru",
    nota: 5.5,
    imdb: 7.6,
    dublado: false,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "13/13", 
    img: "https://m.media-amazon.com/images/M/MV5BOGU4NzQ3YzQtOTU4MC00ZGMzLThlOGMtODMzODg3YzM1Mzg2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Anime de romance genérico, nota genérica, mas o final é (O) e (K) nem OK foi.",
    genre: "1, 4, 9"
  },
  {
    nome: "A Gatherer's Adventure in Isekai",
    nota: 6.5,
    imdb: 6.5,
    dublado: false,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "12/12", 
    img: "https://m.media-amazon.com/images/M/MV5BMmQ2NTkwNDQtZmMwMi00MTZhLWJjNzgtOWUzMGU2MDU3MDI5XkEyXkFqcGc@._V1_.jpg",
    desc: "Tinha tudo para ser bom, mas o ''objetivo'' final foi chato e acabou sem mais nem menos, triste.",
    genre: "5, 7"
  },
  {
    nome: "Jujutsu Kaisen",
    nota: 8.0,
    imdb: 8.5,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "59/59", 
    img: "https://m.media-amazon.com/images/M/MV5BNmI1MmYxNWQtY2E5NC00ZTlmLWIzZGEtNzM1YmE3NDA5NzhjXkEyXkFqcGc@._V1_.jpg",
    desc: "No geral, é legal, e as lutas são bem bonitas. Porém, tem muitos problemas além dos comuns de shōnen, e o anime tem MUITAS cenas de massacre o que não me agrada muito.",
    genre: "2, 7, 10"
  },
  {
    nome: "komi-san can't communicate",
    nota: 8.5,
    imdb: 7.7,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "24/24", 
    img: "https://m.media-amazon.com/images/M/MV5BZGMzZDY0MDUtYzY5OS00NmI0LTlhZmUtZGM2NjVjNjdiNThlXkEyXkFqcGc@._V1_.jpg",
    desc: "Anime MUITO bom, a ideia é boa, a comédia é boa, o romance é no ponto certo, sem acelerar nem focar totalmente, o que é perfeito, e eu não fiquei enjoado vendo, o que é difícil para um Slice of life para mim. (obs. a comi é muito fofa)",
    genre: "4, 9"
  },
  {
    nome: "Blend S",
    nota: 8.0,
    imdb: 6.8,
    dublado: false,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "12/12", 
    img: "https://m.media-amazon.com/images/M/MV5BNzViYzJkODItZDAyMy00NjU1LWEwMzUtOWRlY2Y0YTA3MzM4XkEyXkFqcGc@._V1_.jpg",
    desc: "Que anime gostoso de assistir, todos os episódios conseguem me tirar uma risada sincera, eu só acho que poderia ter um foco maior no atendimento das outras personagens, mas é um ótimo anime, pena que é curtinho.",
    genre: "4, 9"
  },
  {
    nome: "Yu Yu Hakusho",
    nota: 8.7,
    imdb: 8.5,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "112/112", 
    img: "https://m.media-amazon.com/images/M/MV5BNWJmODlhODItZTZmYi00ZGNjLTk1NmYtMjE5M2IwYjI2MzI2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Um clássico atemporal. Mesmo hoje em dia, ele consegue criar uma narrativa legal que te faz pensar sobre a vida no primeiro episódio. O único problema dele é que pega a receita que dá certo e replica várias vezes, mas não deixa de ser bom por conta disso. Recomendo!",
    genre: "2, 10"
  },
  {
    nome: "Beast Tamer",
    nota: 7.5,
    imdb: 6.7,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "13/13", 
    img: "https://m.media-amazon.com/images/M/MV5BZGU4OTdkNjctNTYyYS00M2U4LWE4YjEtZjYzMzVhNmRjYzUzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Isekai/10 Não foge muito de um isekai normal, porém tem algumas partes que me agradaram mais, como o antigo grupo continuar aparecendo na história, ao invés de simplesmente deixar de existir. Dá um ar de que o mundo não gira só em volta do personagem, mas, de resto, ainda é um isekai bem padrão.",
    genre: "5, 7"
  },
  {
    nome: "Date A Live",
    nota: 0.0,
    imdb: 6.9,
    dublado: true,
    finalizado: false,
    emLancamento: true,
    dropado: false,
    brutal: false,
    eps: "0/58", 
    img: "https://m.media-amazon.com/images/M/MV5BM2I5OGRiZWMtYjk1NS00ZGZiLWJiYTktMGJjMGRiNDhlNzI3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "???",
    genre: "1, 3, 4, 8"
  },
  {
    nome: "Fate/strange Fake",
    nota: 0.0,
    imdb: 8.0,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/14", 
    img: "https://m.media-amazon.com/images/M/MV5BMzIyZDNmMmUtMGZkNC00MTJjLTlmYzUtODllYWM5NDQ4YTJjXkEyXkFqcGc@._V1_.jpg",
    desc: "TEMPORARIAMENTE DESCLASSIFICADO POIS É UM SPIN-OFF E PRECISO VER OS PRINCIPAIS PRIMEIRO PRA ENTENDER A LORE",
    genre: "2, 7"
  },
  {
    nome: "The Unaware Atelier Meister",
    nota: 7.7,
    imdb: 6.4,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "12/12", 
    img: "https://m.media-amazon.com/images/M/MV5BNDYxZmY2ZmItZGViMS00ZTUyLWFjOWEtY2UzZDI2NzZhZDc4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Isekai/10 É boa a ideia do personagem que simplesmente não consegue lutar, mas é bom em todo o resto. Isso leva a história para um lado mais legal, sem cair naquele isekai genérico em que o personagem é SUPER FORTE e derrota todo mundo. Mesmo assim, no geral, ainda não foge tanto do isekai genérico.",
    genre: "5, 7"
  },
  {
    nome: "Chainsaw Man",
    nota: 0.0,
    imdb: 8.3,
    dublado: true,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/12", 
    img: "https://m.media-amazon.com/images/M/MV5BZGY2ZTM2MWMtNzA2OS00ZjJlLWIwZTMtMDBhN2EwYjZjZjEyXkEyXkFqcGc@._V1_.jpg",
    desc: "???",
    genre: "2, 3, 10"
  },
  {
    nome: "Life with an Ordinary Guy Who Reincarnated into a Total Fantasy Knockout",
    nota: 5.5,
    imdb: 7.2,
    dublado: false,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "12/12", 
    img: "https://m.media-amazon.com/images/M/MV5BZjAwMGM4NzAtNzMxNi00NGExLWE5MmItOGMzNWJhODI0MTcxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "É um anime BEM abaixo da média. A parte do isekai é simplesmente ruim, e dos combates nem se fala, já que o personagem tem poder infinito. O outro protagonista é completamente inútil e burro, só serve pra atrapalhar, e infelizmente o humor, que era pra ser o principal, não é tão engraçado.",
    genre: "1, 4, 5, 7"
  },
  {
    nome: "Love, Chunibyo & Other Delusions!",
    nota: 0.0,
    imdb: 7.4,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/24",
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSShTomQV1X0sILvFNZ4Hbkeo4xlbCYAZprTQ0P7yJmztjLfcII",
    desc: "???",
    genre: "1, 4, 9"
  },
  {
    nome: "ID: INVADED",
    nota: 7.9,
    imdb: 7.8,
    dublado: true,
    finalizado: true,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "13/13",
    img: "https://m.media-amazon.com/images/M/MV5BZWIwMmUwZGUtNTJiNy00Y2M1LTgxYjItODdhYTc3OGUxMGNkXkEyXkFqcGc@._V1_.jpg",
    desc: "Um bom anime, meio confuso, bem dramático e meio triste. Sinto que tem bastante coisa por trás que eu não entendi e que não é fácil de entender, e ele acaba de um jeito legal. Recomendo.",
    genre: "6, 8"
  },
  {
    nome: "Maken-ki!",
    nota: 0.0,
    imdb: 6.2,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/23",
    img: "https://m.media-amazon.com/images/M/MV5BZTAyNjY5MzAtYWMyNy00MWIyLTk2M2MtYzFhYTYwOWRlNjg0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "???",
    genre: "2, 3, 4"
  },
  {
    nome: "Kämpfer",
    nota: 0.0,
    imdb: 6.3,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/14",
    img: "https://m.media-amazon.com/images/M/MV5BNTQzNGYzNTItNTIzNS00YjQzLTg1ZTctY2M0MDdkZDYwODU2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "???",
    genre: "2, 3, 4, 8"
  },
  {
    nome: "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You",
    nota: 8.5,
    imdb: 7.5,
    dublado: true,
    finalizado: false,
    emLancamento: true,
    dropado: false,
    brutal: false,
    eps: "24/36",
    img: "https://m.media-amazon.com/images/M/MV5BMTc5MTE3MTktN2MwYy00M2UwLTlhMzEtNDE5YjBmMTUzMGRkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "Que anime incrível!!! É bizarro como ele consegue misturar uma comédia boa com drama e romance. As quebras da quarta parede são bizarramente engraçadas, e é loucura como o anime consegue dar atenção para TODAS as personagens, mesmo sendo tantas. Muito bom, recomendo muito!!!(Obs.: Tem muito ecchi, até demais.)",
    genre: "1, 3, 4"
  },
  {
    nome: "Trapped in a Dating Sim: The World of Otome Games Is Tough for Mobs",
    nota: 0.0,
    imdb: 7.3,
    dublado: true,
    finalizado: false,
    emLancamento: true,
    dropado: false,
    brutal: false,
    eps: "0/12",
    img: "https://m.media-amazon.com/images/M/MV5BMzE3OTk2YmQtZmQ2NS00ZGFjLTlkOWItNmExNjExMWYwOTFhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "???",
    genre: "4, 5, 7"
  },
  {
    nome: "Tenpuru",
    nota: 0.0,
    imdb: 6.8,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/13",
    img: "https://m.media-amazon.com/images/M/MV5BMzhiODBjNWQtNzI1Ny00YmY4LTlmYjItMjk0M2Y3MTNiYjUzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "???",
    genre: "1, 3, 4"
  },
  {
    nome: "Dungeon Meshi",
    nota: 0.0,
    imdb: 8.0,
    dublado: true,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/24",
    img: "https://m.media-amazon.com/images/M/MV5BNjRiNzI1MTYtZDg0Mi00NWFiLTg1MWItNjNkMmM5NjU3MWEyXkEyXkFqcGc@._V1_.jpg",
    desc: "???",
    genre: "4, 7"
  },
  {
    nome: "BOFURI: I Don't Want to Get Hurt, so I'll Max Out My Defense.",
    nota: 0.0,
    imdb: 7.5,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/24",
    img: "https://m.media-amazon.com/images/M/MV5BYzNlMWNkN2MtNmJjZi00YjcxLTgwMjEtNjhlODc1Yjg2NGM4XkEyXkFqcGc@._V1_.jpg",
    desc: "???",
    genre: "2, 4, 7"
  },
  {
    nome: "Uzaki-chan wa Asobitai!",
    nota: 0.0,
    imdb: 6.8,
    dublado: true,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/25",
    img: "https://m.media-amazon.com/images/M/MV5BMDQyOTc5NWUtODRmOC00NDUwLWIwOTMtNDBlZTBlOTY3YjA3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "???",
    genre: "1, 4, 9"
  },
  {
    nome: "Maoyuu Maou Yuusha",
    nota: 0.0,
    imdb: 7.1,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/12",
    img: "https://m.media-amazon.com/images/M/MV5BMmY4ZDk3NDktOWMxNS00M2QzLWFhYjMtN2E1ZTVmMDQ5NjIwXkEyXkFqcGc@._V1_.jpg",
    desc: "???",
    genre: "1, 7"
  },
  {
    nome: "A Journey Through Another World: Raising Kids While Adventuring",
    nota: 0.0,
    imdb: 6.7,
    dublado: true,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/12",
    img: "https://m.media-amazon.com/images/M/MV5BNjhjMTYyMDMtMmRjOS00MTYwLTgzMTktNGVhOTZiYjBmOWRmXkEyXkFqcGc@._V1_.jpg",
    desc: "???",
    genre: "5, 7, 9"
  },
  {
    nome: "Back Street Girls: Gokudols",
    nota: 0.0,
    imdb: 7.0,
    dublado: true,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/10",
    img: "https://m.media-amazon.com/images/M/MV5BMjRiZWMzYWQtMDI2NC00OGE2LThkOGMtNDNiYWQ0ZjA2ZmFhXkEyXkFqcGc@._V1_.jpg",
    desc: "???",
    genre: "4, 9"
  },
  {
    nome: "Trigun",
    nota: 0.0,
    imdb: 8.2,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/26",
    img: "https://m.media-amazon.com/images/M/MV5BNjVjZDE0MzEtN2Q1Mi00YjgyLWE0NTMtMWJiNDA5MGRmMmM2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "???",
    genre: "2, 8"
  },
  {
    nome: "Grisaia no Kajitsu",
    nota: 0.0,
    imdb: 7.5,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/24",
    img: "https://m.media-amazon.com/images/M/MV5BYmI2ODI1OTAtMzU4YS00NDUyLWI2MGEtNzQ1NmIxZTk1NDhmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "???",
    genre: "1, 3, 6"
  },
  {
    nome: "Murenase! Seton Gakuen",
    nota: 0.0,
    imdb: 6.9,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/12",
    img: "https://m.media-amazon.com/images/M/MV5BNDdjMGJlOWItYWUyZC00MDI1LWIwM2EtODk4M2NhYjg3MDI5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "???",
    genre: "4, 9"
  },
  {
    nome: "Farming Life in Another World",
    nota: 0.0,
    imdb: 7.2,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/24",
    img: "https://m.media-amazon.com/images/M/MV5BYTY5NWMzNTEtZGIxYS00Yzk4LWE5MmQtYTdmZDVmNzEzYjU3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "???",
    genre: "5, 7, 9"
  },
  {
    nome: "Kono Sekai wa Fukanzen Sugiru",
    nota: 0.0,
    imdb: 6.4,
    dublado: true,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/13",
    img: "https://m.media-amazon.com/images/M/MV5BMTc2MGM2M2EtZGIzNS00ODdhLWJhOWMtZGM1N2I3ZTQ3ZWNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    desc: "???",
    genre: "2, 5, 7"
  },
  {
    nome: "Uma Musume: Pretty Derby",
    nota: 0.0,
    imdb: 7.3,
    dublado: false,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/39",
    img: "https://m.media-amazon.com/images/M/MV5BYTNjOThhZTEtMmQzOC00NmZiLWFiYmItODJlNDM2YTQ4ZTYzXkEyXkFqcGc@._V1_.jpg",
    desc: "???",
    genre: "4, 9"
  },
  {
    nome: "The Case Study of Vanitas",
    nota: 0.0,
    imdb: 7.7,
    dublado: true,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/24",
    img: "https://m.media-amazon.com/images/M/MV5BMzYwMmI1YWMtOTc0My00OGI3LWI3ZDctZmMwYjczYzcxMjI4XkEyXkFqcGc@._V1_.jpg",
    desc: "???",
    genre: "2, 7"
  },
  {
    nome: "The Fragrant Flower Blooms with Dignity",
    nota: 0.0,
    imdb: 8.3,
    dublado: true,
    finalizado: false,
    emLancamento: false,
    dropado: false,
    brutal: false,
    eps: "0/13",
    img: "https://m.media-amazon.com/images/M/MV5BY2Q0NTNlMTAtZGVkYS00NDU1LThjYzYtZDQ3M2U5NGJiNzhkXkEyXkFqcGc@._V1_.jpg",
    desc: "???",
    genre: "1, 4, 6, 9, 10"
  }
];
